[package]
name = "detective"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
bech32 = "0.11"
ark = { package = "ark-lib", version = "0.7.1" }
bitcoin = { workspace = true, features = ["std", "rand-std"] }
bitcoin-payment-instructions = "0.6"
chrono = "0.4"
ciborium = "0.2"
elements = "0.25"
iso_currency = "0.5"
lightning = { version = "0.2", default-features = false, features = ["std"] }
lightning-invoice = { version = "0.34", features = ["std"] }
lightning-net-tokio = "0.2"
lightning-rapid-gossip-sync = "0.2"
lnurl-rs = { version = "0.10", default-features = false }
log = "0.4"
percent-encoding-rfc3986 = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
silentpayments = { version = "0.4", default-features = false }
thousands = "0.2"
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
tokio-stream.workspace = true
urlencoding.workspace = true
