[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
askama = "0.14"
axum = { version = "0.8", features = ["json"] }
build_html = "2"
bitcoin = { workspace = true, features = ["std"] }
bytes = "1"
detective.workspace = true
futures-util = "0.3"
rand = "0.8"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
urlencoding.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
